const STORAGE_KEY='memo-pad-notes-v3',TRASH_KEY='memo-pad-trash-v1',SETTINGS_KEY='memo-pad-settings-v1',THEME_KEY='memo-pad-theme-v1';
const $=(s)=>document.querySelector(s),text={untitled:'\uc81c\ubaa9 \uc5c6\uc74c',empty:'\ub0b4\uc6a9 \uc5c6\uc74c',saved:'\uc790\ub3d9 \uc800\uc7a5\ub428',saving:'\uc800\uc7a5 \uc911\u2026',updated:'\ub9c8\uc9c0\ub9c9 \uc218\uc815'};
const defaults={autoTitle:true,categories:true,tags:true,bookmarks:true,trash:true,history:true,historyLimit:20,shortcuts:true};
let notes=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('memo-pad-notes-v2')||localStorage.getItem('memo-pad-notes-v1')||'[]'),trash=JSON.parse(localStorage.getItem(TRASH_KEY)||'[]'),settings={...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')},activeId=notes[0]?.id||null,view='notes',saveTimer;
const list=$('#noteList'),title=$('#noteTitle'),content=$('#noteContent'),category=$('#noteCategory'),tags=$('#noteTags'),status=$('#saveStatus'),updatedAt=$('#updatedAt'),charCount=$('#charCount'),search=$('#searchNotes'),categoryFilter=$('#categoryFilter'),template=$('#emptyState');
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(notes));localStorage.setItem(TRASH_KEY,JSON.stringify(trash));localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
function source(){return view==='trash'?trash:notes} function activeNote(){return source().find(n=>n.id===activeId)} function label(n){return n.title.trim()||text.untitled} function esc(v){const e=document.createElement('span');e.textContent=v;return e.innerHTML} function date(v){return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))} function noteTags(n){return Array.isArray(n.tags)?n.tags:[]}
function normalize(n){return {...n,category:n.category||'',tags:noteTags(n),pinned:!!n.pinned,history:Array.isArray(n.history)?n.history:[]}}
notes=notes.map(normalize);trash=trash.map(normalize);
function renderCategories(){const current=categoryFilter.value;const values=[...new Set(notes.map(n=>n.category.trim()).filter(Boolean))].sort();categoryFilter.innerHTML=`<option value="">\ubaa8\ub4e0 \uce74\ud14c\uace0\ub9ac</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}`;categoryFilter.value=values.includes(current)?current:'';}
function renderList(){renderCategories();const query=search.value.trim().toLowerCase(),filter=categoryFilter.value;const visible=source().slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt).filter(n=>(!query||`${n.title} ${n.content} ${n.category} ${noteTags(n).join(' ')}`.toLowerCase().includes(query))&&(!filter||n.category===filter));list.replaceChildren();visible.forEach(n=>{const b=document.createElement('button');b.className=`note-card${n.id===activeId?' active':''}`;const meta=[n.category,...noteTags(n).map(t=>`#${t}`)].filter(Boolean).join(' \u00b7 ');b.innerHTML=`<strong>${settings.bookmarks&&n.pinned?'&#9733; ':''}${esc(label(n))}</strong><span>${esc(meta||n.content.trim()||text.empty)}</span>`;b.onclick=()=>{activeId=n.id;render()};list.append(b)});$('#noteCount').textContent=query?`${visible.length}\uac1c \uac80\uc0c9\ub428`:`${source().length}\uac1c\uc758 ${view==='trash'?'\ud734\uc9c0\ud1b5 \uba54\ubaa8':'\uba54\ubaa8'}`}
function setHidden(ids,hidden){ids.forEach(id=>$(id).hidden=hidden)}
function render(){renderList();const n=activeNote(),isTrash=view==='trash';const normal=['#pinNote','#historyButton','#duplicateNote','#downloadNote','#deleteNote'],trashButtons=['#restoreNote','#permanentDelete'];if(!n){setHidden(['#noteTitle','#noteMeta','#noteContent','.editor-footer',...normal,...trashButtons],true);if(!$('.empty-state'))$('.editor').append(template.content.cloneNode(true));return}$('.empty-state')?.remove();setHidden(['#noteTitle','#noteMeta','#noteContent','.editor-footer'],false);setHidden(normal,isTrash);setHidden(trashButtons,!isTrash);title.value=n.title;content.value=n.content;category.value=n.category;tags.value=noteTags(n).join(', ');[title,content,category,tags].forEach(el=>el.readOnly=isTrash);$('#pinNote').hidden=isTrash||!settings.bookmarks;$('#historyButton').hidden=isTrash||!settings.history;category.hidden=!settings.categories;tags.hidden=!settings.tags;$('#noteMeta').hidden=!settings.categories&&!settings.tags;updatedAt.textContent=`${text.updated} \u00b7 ${date(n.updatedAt)}`;updateCount()}
function updateCount(){charCount.textContent=`${content.value.length.toLocaleString('ko-KR')}\uc790`}
function snapshot(n){return {title:n.title,content:n.content,category:n.category,tags:[...noteTags(n)],updatedAt:n.updatedAt}}
function newNote(){view='notes';setView();const n=normalize({id:crypto.randomUUID(),title:'',content:'',updatedAt:Date.now()});notes.unshift(n);activeId=n.id;persist();render();title.focus()}
function saveNote(){const n=activeNote();if(!n||view==='trash')return;const newTitle=title.value.trim()|| (settings.autoTitle?content.value.split(/\r?\n/).find(v=>v.trim())?.trim().slice(0,120)||'':'');const next={title:newTitle,content:content.value,category:settings.categories?category.value.trim():'',tags:settings.tags?[...new Set(tags.value.split(',').map(v=>v.trim()).filter(Boolean))]:[]};if(settings.history&&(n.title!==next.title||n.content!==next.content||n.category!==next.category||JSON.stringify(noteTags(n))!==JSON.stringify(next.tags))){n.history=[snapshot(n),...n.history].slice(0,Math.max(5,Number(settings.historyLimit)||20))}Object.assign(n,next,{updatedAt:Date.now()});title.value=n.title;persist();renderList();updatedAt.textContent=`${text.updated} \u00b7 ${date(n.updatedAt)}`;status.textContent=text.saved}
function scheduleSave(){status.textContent=text.saving;updateCount();clearTimeout(saveTimer);saveTimer=setTimeout(saveNote,350)}
function moveToTrash(){const n=activeNote();if(!n)return;if(!settings.trash){if(confirm('\uc774 \uba54\ubaa8\ub97c \uc644\uc804\ud788 \uc0ad\uc81c\ud560\uae4c\uc694?'))permanentDelete(false);return}if(!confirm('\uba54\ubaa8\ub97c \ud734\uc9c0\ud1b5\uc5d0 \uc62e\uae38\uae4c\uc694?'))return;trash.unshift({...n,deletedAt:Date.now()});notes=notes.filter(x=>x.id!==n.id);activeId=notes[0]?.id||null;persist();render()}
function permanentDelete(confirmFirst=true){const n=activeNote();if(!n)return;if(confirmFirst&&!confirm('\uc774 \uba54\ubaa8\ub97c \uc644\uc804\ud788 \uc0ad\uc81c\ud560\uae4c\uc694?'))return;trash=trash.filter(x=>x.id!==n.id);activeId=trash[0]?.id||null;persist();render()}
function restore(){const n=activeNote();if(!n)return;trash=trash.filter(x=>x.id!==n.id);delete n.deletedAt;notes.unshift(n);view='notes';activeId=n.id;persist();setView();render()}
function togglePin(){const n=activeNote();if(!n)return;n.pinned=!n.pinned;n.updatedAt=Date.now();persist();render()}
function duplicate(){const n=activeNote();if(!n)return;const copy=normalize({...n,id:crypto.randomUUID(),title:n.title.trim()?`${n.title} \ubcf5\uc0ac\ubcf8`:'',pinned:false,history:[],updatedAt:Date.now()});notes.unshift(copy);activeId=copy.id;persist();render();title.focus()}
function download(){const n=activeNote();if(!n)return;const name=prompt('\ud30c\uc77c \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694.',label(n));if(name===null)return;const safe=(name.trim()||label(n)).replace(/[\\/:*?"<>|]/g,'_'),blob=new Blob([`${label(n)}\n\n${n.content}`],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safe}.txt`;a.click();URL.revokeObjectURL(a.href)}
async function importText(e){const file=e.target.files[0];if(!file)return;const n=normalize({id:crypto.randomUUID(),title:file.name.replace(/\.txt$/i,''),content:await file.text(),updatedAt:Date.now()});notes.unshift(n);activeId=n.id;e.target.value='';persist();render()}
function backupAll(){const name=prompt('\ubc31\uc5c5 \ud30c\uc77c \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694.',`blco-memo-${new Date().toISOString().slice(0,10)}`);if(name===null)return;const safe=(name.trim()||'blco-memo').replace(/[\\/:*?"<>|]/g,'_'),blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),notes,trash,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safe}.json`;a.click();URL.revokeObjectURL(a.href)}
function showHistory(){const n=activeNote();if(!n)return;const box=$('#historyList');box.replaceChildren();if(!n.history.length)box.textContent='\uc800\uc7a5\ub41c \ubc84\uc804\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.';n.history.forEach((v,i)=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<strong>${esc(v.title||text.untitled)}</strong><span>${date(v.updatedAt)}</span><button type="button" data-index="${i}" class="secondary-button">\uc774 \ubc84\uc804 \ubcf5\uc6d0</button>`;box.append(d)});box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const old=n.history[Number(b.dataset.index)];n.history=[snapshot(n),...n.history].slice(0,Math.max(5,Number(settings.historyLimit)||20));Object.assign(n,{...old,updatedAt:Date.now()});persist();$('#historyDialog').close();render()});$('#historyDialog').showModal()}
function setView(){const trashView=view==='trash';$('#trashButton').classList.toggle('active',trashView);$('#allNotesButton').classList.toggle('active',!trashView);categoryFilter.hidden=trashView||!settings.categories;activeId=source()[0]?.id||activeId;render()}
function openSettings(){['AutoTitle','Categories','Tags','Bookmarks','Trash','History','Shortcuts'].forEach(k=>{$(`#setting${k}`).checked=settings[k[0].toLowerCase()+k.slice(1)]});$('#settingHistoryLimit').value=settings.historyLimit;$('#settingsDialog').showModal()}
function saveSettings(){settings={autoTitle:$('#settingAutoTitle').checked,categories:$('#settingCategories').checked,tags:$('#settingTags').checked,bookmarks:$('#settingBookmarks').checked,trash:$('#settingTrash').checked,history:$('#settingHistory').checked,historyLimit:Math.min(100,Math.max(5,Number($('#settingHistoryLimit').value)||20)),shortcuts:$('#settingShortcuts').checked};persist();$('#settingsDialog').close();setView()}
$('#newNote').onclick=newNote;$('#deleteNote').onclick=moveToTrash;$('#permanentDelete').onclick=()=>permanentDelete();$('#restoreNote').onclick=restore;$('#downloadNote').onclick=download;$('#pinNote').onclick=togglePin;$('#duplicateNote').onclick=duplicate;$('#historyButton').onclick=showHistory;$('#importFile').onchange=importText;$('#backupNotes').onclick=backupAll;$('#settingsButton').onclick=openSettings;$('#saveSettings').onclick=saveSettings;$('#allNotesButton').onclick=()=>{view='notes';activeId=notes[0]?.id||null;setView()};$('#trashButton').onclick=()=>{view='trash';activeId=trash[0]?.id||null;setView()};[title,content,category,tags].forEach(e=>e.oninput=scheduleSave);search.oninput=renderList;categoryFilter.onchange=renderList;
const systemTheme=window.matchMedia('(prefers-color-scheme: dark)');function applyTheme(dark){document.body.classList.toggle('dark',dark);$('#themeToggle').textContent=dark?'\u2600':'\u263e'}const savedTheme=localStorage.getItem(THEME_KEY);applyTheme(savedTheme?savedTheme==='dark':systemTheme.matches);$('#themeToggle').onclick=()=>{const dark=!document.body.classList.contains('dark');applyTheme(dark);localStorage.setItem(THEME_KEY,dark?'dark':'light')};systemTheme.addEventListener('change',e=>{if(!localStorage.getItem(THEME_KEY))applyTheme(e.matches)});
document.addEventListener('keydown',e=>{if(!settings.shortcuts||e.target.matches('input,textarea,select'))return;const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(mod&&key==='n'){e.preventDefault();newNote()}if(mod&&key==='f'){e.preventDefault();search.focus()}if(mod&&e.shiftKey&&key==='d'){e.preventDefault();duplicate()}if(mod&&e.shiftKey&&key==='b'){e.preventDefault();togglePin()}});$('#year').textContent=new Date().getFullYear();setView();
